language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "IpUOtFTBE5enOCVVmGbL9Mt0apfHaz/Hb40htAvi7iUkhFHEDfDjxOoionMf43P6Cr8+jmghQS5VM0LPH+OLaWSG7FQlHE4LsyDOYgI/+cdf9DVpYslNeEe0f8ZpPOxQa4wwf+5OebVkU1MWeCh1ss42UjWN09i868P1ndcMzpcLNE9GkBAphNskKwdoTCldEuwY4VDZ2Vz7bh/A5iYEHtJWRLXzyT19r5XpYtGnqvl8f25gKi9wcsCXuRz/3ovBMrCk7Q+ENuoOgtKe4qsKUHPye9sFOHBsThDhpeAS7qotBqBcDlUjM3T6Hc2LVGYSVMqrZ+oGo4rJQ+KcQVLxoGA+bQtXWY3T+/V/2SYPFMvS91sIY5F7E/F98mgipJs83QbO1w1w49fqYxIls9VgPTgP0jlQJElF05EUrDzZny24k5ipKlck0k55biE0S3+cM0FGOOpGZ4aYt4DVpmVhTreA9COQ+pawKJWRsCs2PUJSkNUZZII5ljBjq49Qh3QZpDDn1usHzTRNPtZEcl374vRjD5VfhhZD/GyoFfex5RIgXrKAIGM1bl1aJXoyvPi1HP9y8Wmt6TdRmc5HdWtO74wMscn+k62V1jwjmNVyqO+mwA4asYItxwHZ4BPxwPsh3ftC/6odzI6I9nRIO9NHkwzyIa5x6Tl0qw7qzQbnQRY="
