language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "RoE6wjkpjJL1UKGjaLhPxc5huPAads/L9DCI1DcJwRIg1BSAn3q/kTbuzEOGt6etnQmTos0irZ0t2yujuSeI2usglZwXKAsLnCqrFEAJY5/bf0kpqkpWDZ/T4ACmc8msPF+9dL2lXrPEAy8py49hJx0UNu4fhPFmhIb6XB709566OsNdXIk5k/Czkx0J1yTGgKI8yPxoxk/5vvY+5+YH1t8BI1/A0i36NsNv2PCRmavsL3sTghH/Nd9fkQfGDnaZt6ettiptfRUKIurvd8tKJBy2UhMffIlAt9YdVTYxmW3lLupNPYjAwWWgPaHlbuD29fJR7pDYTZmxhGazSYlCeNaeIsPA39q6nrvu1n4F08EVX4NgRFWJ9eqjj9SuE1FPleD0nhKjgTdwPG/ZyUXAHqTtnKP8JcGoAhi2QGKS/bzdK3uEbPJ8lRB36ZMT3sQkN3NVkCYADRdY7XmrFd9+GnAi7ezlxWZH+o2NVyuT0lLbxJt9jSOYgDwzMWYW+D92aZtt7RvIppE0OU/eabEgLHU/wznb1yAMNaIJjvLP6zxr5yARXhIeEcr6HHtjJFsuUocZGwuLJdneBzfEMouE8aVcbkmdrGNSCwUPmFluv7u/1aS3KZpFuxgLMpuusyeWBzzPOyGwBJGugVcgdRQRfLzLX9aA+sVF63BYiRPsxtA="
